project:
  type: website

website:
  title: "NRS RAP Book"
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: RAP in NRS
        contents: 
        - rap-in-nrs/why-rap.qmd
        - text: RAP Support
          href: rap-in-nrs/rap-support.qmd
        - rap-in-nrs/getting-started.qmd
      - section: Guidance
        contents:
        - guidance/process-mapping.qmd
      - section: Training
        href: training/index.qmd
        contents:
        - training/Using-Devops.qmd
      - blog/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



