name: Spellcheck
on:
  push:
  pull_request:
jobs:
  Spelling:
    runs-on: ubuntu-latest
    container: {image: "rocker/tidyverse:4.2.1"}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install spelling
        run: if (!require("spelling")) install.packages("spelling")
        shell: Rscript {0}
      
      - name: Install testthat
        run: if (!require("testthat")) install.packages("testthat")
        shell: Rscript {0}
      
      - name: Run Spelling Check test
        run: spelling::spell_check_files(list.files(pattern = ".*.qmd$", recursive = TRUE), ignore = readr::read_lines("sp_ignore_wordlist.txt"))
        shell: Rscript {0}
        
      - name: Halt if spelling errors 
          run: testthat::test_that(
          desc = "No Errors", 
          code = {
            no_error <- spelling::spell_check_files(path = "sp_ignore_wordlist.txt", ignore = readr::read_lines("sp_ignore_wordlist.txt"))
            spellcheck <- spelling::spell_check_files(list.files(pattern = ".*.qmd$", recursive = TRUE), lang = "en-GB",  ignore = readr::read_lines("sp_ignore_wordlist.txt"))
            testthat::expect_equal(object = print(spellcheck), expected = print(no_error))
              })
        shell: Rscript {0}
        